"""Typed response chunks streamed to the frontend.

Each line the backend writes to the ``/api/query`` response body is one
serialized chunk from this module. The models are the source of truth for the
frontend's TypeScript types, regenerated by ``mise run generate-types``.
"""

from typing import Literal

from pydantic import BaseModel, Field


class TextChunk(BaseModel):
    """A fragment of the assistant's answer text."""

    type: Literal["text"] = "text"
    content: str = Field(description="The message text")


class ReasoningChunk(BaseModel):
    """A model "thought", surfaced only when ``SHOW_MODEL_THINKING`` is enabled."""

    type: Literal["reasoning"] = "reasoning"
    content: str = Field(description="The model reasoning")


class LetterChunk(BaseModel):
    """Completed letter content, rendered in the letter panel rather than inline."""

    type: Literal["letter"] = "letter"
    content: str = Field(description="The letter content")


class EndOfStreamChunk(BaseModel):
    """Sentinel marking clean completion; not appended to the message content."""

    type: Literal["end_of_stream"] = "end_of_stream"


ResponseChunk = TextChunk | ReasoningChunk | LetterChunk | EndOfStreamChunk
"""Discriminated union of every chunk type, distinguished by the ``type`` field."""
